// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/HelloGreet.proto

package org.test.grpc.greet.model;

public interface GreetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.greet.model.GreetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sum = 1;</code>
   * @return The sum.
   */
  int getSum();
}
