// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/HelloGreet.proto

package org.test.grpc.greet.model;

public interface GreetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:test.greet.model.GreetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 firstV = 1;</code>
   * @return The firstV.
   */
  int getFirstV();

  /**
   * <code>int32 secondV = 2;</code>
   * @return The secondV.
   */
  int getSecondV();
}
