// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/HelloGreet.proto

package org.test.grpc.greet.model;

public final class HelloGreet {
  private HelloGreet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_greet_model_GreetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_greet_model_GreetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_test_greet_model_GreetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_test_greet_model_GreetResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025test/HelloGreet.proto\022\020test.greet.mode" +
      "l\"/\n\014GreetRequest\022\016\n\006firstV\030\001 \001(\005\022\017\n\007sec" +
      "ondV\030\002 \001(\005\"\034\n\rGreetResponse\022\013\n\003sum\030\001 \001(\005" +
      "B\035\n\031org.test.grpc.greet.modelP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_test_greet_model_GreetRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_test_greet_model_GreetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_greet_model_GreetRequest_descriptor,
        new String[] { "FirstV", "SecondV", });
    internal_static_test_greet_model_GreetResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_test_greet_model_GreetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_test_greet_model_GreetResponse_descriptor,
        new String[] { "Sum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
